name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download LocalXpose
      run: Invoke-WebRequest https://api.localxpose.io/api/downloads/loclx-windows-amd64.zip -OutFile lx.zip

    - name: Extract LocalXpose
      run: Expand-Archive lx.zip -DestinationPath lx

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set runneradmin password
      run: |
        $password = ConvertTo-SecureString "${{ secrets.USER_PASSWORD }}" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $password

    - name: Start LocalXpose TCP Tunnel (RDP)
      run: .\lx\lx.exe tcp --port 3389 --token $Env:LOCX_TOKEN
      env:
        LOCX_TOKEN: ${{ secrets.LOCX_TOKEN }}
